### ISSUE TITLE
shiny app for cincy package

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/cincy#24]
- download geographic data
- upload tract-level data to convert

**Comment by cole-brokamp** [comment]
side-by-side tmaps; select one layer for each of all possible geographies in {cincy}

**Comment by erikarasnick** [comment]
`tmap::tm_facets()` has an argument called `as.layers`... When `FALSE` you get two side-by-side maps with the interactive hover, but you cannot select and deselect variables as layers (the menu only shows the name of the entire data.frame). When `TRUE` you get one map and can select and deselect the variables as layers.

looking for workarounds or alternatives...
