### ISSUE TITLE
interactive linked maps on cincy vignette is broken

### ISSUE THREAD

**Issue by cole-brokamp** [geomarker-io/cincy#30]

**Comment by erikarasnick** [comment]
works locally for me

**Comment by cole-brokamp** [comment]
me too, its something with the github deployment pages.  I'll take a look, maybe we can just build the site locally and put it in a `docs` folder rather than relying on gha to push to another branch

**Comment by erikarasnick** [comment]
built site locally and deployed from docs folder rather than from gh-pages branch, and it's working
