### ISSUE TITLE
unexpected interpolate behavior when geography id columns have same name

### ISSUE THREAD

**Issue by erikarasnick** [geomarker-io/cincy#31]
https://github.com/geomarker-io/cincy/blob/01d93ce237deac9b807ac7981989a8e1eb536593/R/interpolate.R#L73'

when `from_id` and `to_id` have the same name, this gets grouped by whichever one is first in the data (usually `from_id` instead of `to_id`)

example: 
```
interpolate(from = cincy::tract_tigris_2020 |> filter(census_tract_id %in% c("39061026104", "39061026103")),
to = cincy::tract_tigris_2010 |> filter(census_tract_id == "39061026101"), 
wt = "pop")
```
returns missing values for `39061026101`

but 
```
interpolate(from = cincy::tract_tigris_2020 |> filter(census_tract_id %in% c("39061026104", "39061026103")) |> rename(census_tract_id_2020 = census_tract_id),
to = cincy::tract_tigris_2010 |> filter(census_tract_id == "39061026101") |> rename(census_tract_id_2010 = census_tract_id), 
wt = "pop")
```
works as expected.

**Comment by cole-brokamp** [comment]
Thanks for the details.  There could be a way to fix it in the function, but it might be simpler to enforce this at the beginning of the function with a:

```r
if (from_id == to_id) stop("geography columns in from and to must have distinct names")
```

Could you open a PR for this *and* also include the "TODO" things listed in code here too?:

https://github.com/geomarker-io/cincy/blob/01d93ce237deac9b807ac7981989a8e1eb536593/R/interpolate.R#L33
